In [2]:
!pip install nltk

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Akhila\PROJECTS\sentment_analysis(MICROIT)(i)\dataset\tweets.csv")  # Replace with your file path
df



tweet_id airline_sentiment  asentiment_confidence  \
0      5.703060e+17           neutral                 1.0000   
1      5.703010e+17          positive                 0.3486   
2      5.703010e+17           neutral                 0.6837   
3      5.703010e+17          negative                 1.0000   
4      5.703010e+17          negative                 1.0000   
...             ...               ...                    ...   
14635  5.695880e+17          positive                 0.3487   
14636  5.695870e+17          negative                 1.0000   
14637  5.695870e+17           neutral                 1.0000   
14638  5.695870e+17          negative                 1.0000   
14639  5.695870e+17           neutral                 0.6771   

      airline_sentiment_confidence  negativereason_confidence         airline  \
0                              NaN                        NaN  Virgin America   
1                              NaN                     0.0000  Virgin America   
2                              NaN                        NaN  Virgin America   
3                       Bad Flight                     0.7033  Virgin America   
4                       Can't Tell                     1.0000  Virgin America   
...                            ...                        ...             ...   
14635                          NaN                     0.0000        American   
14636       Customer Service Issue                     1.0000        American   
14637                          NaN                        NaN        American   
14638       Customer Service Issue                     0.6659        American   
14639                          NaN                     0.0000        American   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN          cairdin                 NaN   
1                        NaN         jnardino                 NaN   
2                        NaN       yvonnalynn                 NaN   
3                        NaN         jnardino                 NaN   
4                        NaN         jnardino                 NaN   
...                      ...              ...                 ...   
14635                    NaN  KristenReenders                 NaN   
14636                    NaN         itsropes                 NaN   
14637                    NaN         sanyabun                 NaN   
14638                    NaN       SraJackson                 NaN   
14639                    NaN        daviddtwu                 NaN   

       retweet_count                                               text  \
0                  0                @VirginAmerica What @dhepburn said.   
1                  0  @VirginAmerica plus you've added commercials t...   
2                  0  @VirginAmerica I didn't today... Must mean I n...   
3                  0  @VirginAmerica it's really aggressive to blast...   
4                  0  @VirginAmerica and it's a really big bad thing...   
...              ...                                                ...   
14635              0  @AmericanAir thank you we got on a different f...   
14636              0  @AmericanAir leaving over 20 minutes Late Flig...   
14637              0  @AmericanAir Please bring American Airlines to...   
14638              0  @AmericanAir you have my money, you change my ...   
14639              0  @AmericanAir we have 8 ppl so we need 2 know h...   

      tweet_coord     tweet_created tweet_location               user_timezone  
0             NaN  24-02-2015 11:35            NaN  Eastern Time (US & Canada)  
1             NaN  24-02-2015 11:15            NaN  Pacific Time (US & Canada)  
2             NaN  24-02-2015 11:15      Lets Play  Central Time (US & Canada)  
3             NaN  24-02-2015 11:15            NaN  Pacific Time (US & Canada)  
4             NaN  24-02-2015 11:14            NaN  Pacific Time (US & Canada)  
...           ...               ...            ...   

In [2]:
df.head()

tweet_id airline_sentiment  asentiment_confidence  \
0  5.703060e+17           neutral                 1.0000   
1  5.703010e+17          positive                 0.3486   
2  5.703010e+17           neutral                 0.6837   
3  5.703010e+17          negative                 1.0000   
4  5.703010e+17          negative                 1.0000   

  airline_sentiment_confidence  negativereason_confidence         airline  \
0                          NaN                        NaN  Virgin America   
1                          NaN                     0.0000  Virgin America   
2                          NaN                        NaN  Virgin America   
3                   Bad Flight                     0.7033  Virgin America   
4                   Can't Tell                     1.0000  Virgin America   

  airline_sentiment_gold        name negativereason_gold  retweet_count  \
0                    NaN     cairdin                 NaN              0   
1                    NaN    jnardino                 NaN              0   
2                    NaN  yvonnalynn                 NaN              0   
3                    NaN    jnardino                 NaN              0   
4                    NaN    jnardino                 NaN              0   

                                                text tweet_coord  \
0                @VirginAmerica What @dhepburn said.         NaN   
1  @VirginAmerica plus you've added commercials t...         NaN   
2  @VirginAmerica I didn't today... Must mean I n...         NaN   
3  @VirginAmerica it's really aggressive to blast...         NaN   
4  @VirginAmerica and it's a really big bad thing...         NaN   

      tweet_created tweet_location               user_timezone  
0  24-02-2015 11:35            NaN  Eastern Time (US & Canada)  
1  24-02-2015 11:15            NaN  Pacific Time (US & Canada)  
2  24-02-2015 11:15      Lets Play  Central Time (US & Canada)  
3  24-02-2015 11:15            NaN  Pacific Time (US & Canada)  
4  24-02-2015 11:14            NaN  Pacific Time (US & Canada)

In [3]:
print(df.columns)      # Check column names


Index(['tweet_id', 'airline_sentiment', 'asentiment_confidence',
       'airline_sentiment_confidence', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='object')


In [4]:
print(df['text'].isnull().sum())  # Check for missing values


0


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=100)  # You can tweak max_features
X = tfidf.fit_transform(df['text']).toarray()  # Feature matrix


In [6]:
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df['text']).toarray()


In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['airline_sentiment'])  # Converts labels to numeric form like 0,1,2


In [10]:
print(list(zip(le.classes_, le.transform(le.classes_))))


[('negative', 0), ('neutral', 1), ('positive', 2)]


In [11]:
from sklearn.model_selection import train_test_split

# X is your TF-IDF matrix, y is your encoded sentiment labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()                                                #TRAINING MODEL
model.fit(X_train, y_train)


LogisticRegression()

In [13]:
y_pred = model.predict(X_test)
y_pred


array([2, 0, 0, ..., 1, 2, 1])

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)      # Train the model

y_pred = model.predict(X_test)   # Predict class labels on test set


In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))


print("\nClassification Report:\n", classification_report(y_test, y_pred))                 #EVALUATION OF  MODEL


print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.8036202185792349

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.93      0.88      1889
           1       0.67      0.53      0.59       580
           2       0.80      0.61      0.69       459

    accuracy                           0.80      2928
   macro avg       0.77      0.69      0.72      2928
weighted avg       0.80      0.80      0.79      2928


Confusion Matrix:
 [[1766   93   30]
 [ 233  307   40]
 [ 119   60  280]]


In [16]:
print(type(y_pred))      # should be numpy.ndarray
print(y_pred.shape)      # should be (number_of_test_samples,)
print(y_pred[:10])       # first 10 predicted labels, should be integers like 0,1,2


<class 'numpy.ndarray'>
(2928,)
[2 0 0 1 1 0 0 1 0 2]


In [17]:
import pickle

with open('sentiment_model.pkl', 'wb') as f:
    pickle.dump(model, f)                                                           #SAVING THE MODEL

with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf, f)


with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

